[book]
authors = ["Cardinal Cryptography"]
language = "en"
description = "Documentation of the rust implementation of Aleph protocol"
multilingual = false
src = "docs"
title = "Rush - Aleph in Rust"

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false
