use crate::{
    alerts::{Alert, ForkingNotification, NetworkMessage},
    creation,
    dag::{Dag, DagResult, DagStatus, DagUnit, Request as ReconstructionRequest},
    extension::Ordering,
    handle_task_termination,
    member::UnitMessage,
    units::{
        SignedUnit, UncheckedSignedUnit, Unit, UnitCoord, UnitStore, UnitStoreStatus,
        UnitWithParents, Validator, WrappedUnit,
    },
    Config, Data, DataProvider, FinalizationHandler, Hasher, Index, Keychain, MultiKeychain,
    NodeIndex, Receiver, Round, Sender, Signature, Signed, SpawnHandle, Terminator,
    UncheckedSigned,
};
use aleph_bft_types::Recipient;
use futures::{
    channel::{mpsc, oneshot},
    future::pending,
    pin_mut, AsyncRead, AsyncWrite, Future, FutureExt, StreamExt,
};
use futures_timer::Delay;
use itertools::Itertools;
use log::{debug, error, info, trace, warn};
use std::{
    cmp::max,
    collections::HashSet,
    convert::TryFrom,
    fmt::{Display, Formatter, Result as FmtResult},
    marker::PhantomData,
    time::Duration,
};

mod collection;

use crate::backup::{BackupLoader, BackupSaver};
#[cfg(feature = "initial_unit_collection")]
use collection::{Collection, IO as CollectionIO};
pub use collection::{NewestUnitResponse, Salt};

/// Possible requests for information from other nodes.
pub enum Request<H: Hasher> {
    Coord(UnitCoord),
    Parents(H::Hash),
    NewestUnit(Salt),
}

pub(crate) enum Response<H: Hasher, D: Data, S: Signature> {
    Coord(UncheckedSignedUnit<H, D, S>),
    Parents(H::Hash, Vec<UncheckedSignedUnit<H, D, S>>),
    NewestUnit(UncheckedSigned<NewestUnitResponse<H, D, S>, S>),
}

pub(crate) enum RunwayNotificationOut<H: Hasher, D: Data, S: Signature> {
    /// A new unit was generated by this runway
    NewSelfUnit(UncheckedSignedUnit<H, D, S>),
    /// A new unit was generated by this runway or imported from outside and added to the DAG
    NewAnyUnit(UncheckedSignedUnit<H, D, S>),
    Request(Request<H>),
    Response(Response<H, D, S>, NodeIndex),
}

pub(crate) enum RunwayNotificationIn<H: Hasher, D: Data, S: Signature> {
    NewUnit(UncheckedSignedUnit<H, D, S>),
    Request(Request<H>, NodeIndex),
    Response(Response<H, D, S>),
}

impl<H: Hasher, D: Data, S: Signature> TryFrom<UnitMessage<H, D, S>>
    for RunwayNotificationIn<H, D, S>
{
    type Error = ();

    fn try_from(message: UnitMessage<H, D, S>) -> Result<Self, Self::Error> {
        let result = match message {
            UnitMessage::NewUnit(u) => RunwayNotificationIn::NewUnit(u),
            UnitMessage::RequestCoord(node_id, coord) => {
                RunwayNotificationIn::Request(Request::Coord(coord), node_id)
            }
            UnitMessage::RequestParents(node_id, u_hash) => {
                RunwayNotificationIn::Request(Request::Parents(u_hash), node_id)
            }
            UnitMessage::ResponseCoord(u) => RunwayNotificationIn::Response(Response::Coord(u)),
            UnitMessage::ResponseParents(u_hash, parents) => {
                RunwayNotificationIn::Response(Response::Parents(u_hash, parents))
            }
            UnitMessage::RequestNewest(node_id, salt) => {
                RunwayNotificationIn::Request(Request::NewestUnit(salt), node_id)
            }
            UnitMessage::ResponseNewest(response) => {
                RunwayNotificationIn::Response(Response::NewestUnit(response))
            }
        };
        Ok(result)
    }
}

type CollectionResponse<H, D, MK> = UncheckedSigned<
    NewestUnitResponse<H, D, <MK as Keychain>::Signature>,
    <MK as Keychain>::Signature,
>;

struct Runway<H, D, FH, MK>
where
    H: Hasher,
    D: Data,
    FH: FinalizationHandler<D>,
    MK: MultiKeychain,
{
    missing_coords: HashSet<UnitCoord>,
    missing_parents: HashSet<H::Hash>,
    store: UnitStore<DagUnit<H, D, MK>>,
    keychain: MK,
    dag: Dag<H, D, MK>,
    ordering: Ordering<H, D, MK, FH>,
    alerts_for_alerter: Sender<Alert<H, D, MK::Signature>>,
    notifications_from_alerter: Receiver<ForkingNotification<H, D, MK::Signature>>,
    unit_messages_from_network: Receiver<RunwayNotificationIn<H, D, MK::Signature>>,
    unit_messages_for_network: Sender<RunwayNotificationOut<H, D, MK::Signature>>,
    responses_for_collection: Sender<CollectionResponse<H, D, MK>>,
    resolved_requests: Sender<Request<H>>,
    parents_for_creator: Sender<DagUnit<H, D, MK>>,
    backup_units_for_saver: Sender<DagUnit<H, D, MK>>,
    backup_units_from_saver: Receiver<DagUnit<H, D, MK>>,
    new_units_from_creation: Receiver<SignedUnit<H, D, MK>>,
    exiting: bool,
}

struct RunwayStatus<'a, H: Hasher> {
    missing_coords: &'a HashSet<UnitCoord>,
    missing_parents: &'a HashSet<H::Hash>,
    dag_status: DagStatus,
    store_status: UnitStoreStatus,
}

impl<'a, H: Hasher> RunwayStatus<'a, H> {
    fn short_report(&self) -> String {
        let rounds_behind = max(self.dag_status.top_round(), self.store_status.top_round())
            - self.store_status.top_round();
        let missing_coords = self.missing_coords.len();
        match (rounds_behind, missing_coords) {
            (0..=2, 0) => "healthy".to_string(),
            (0..=2, 1..) => format!("syncing - missing {missing_coords} unit(s)"),
            (3.., 0) => format!("behind by {rounds_behind} rounds"),
            _ => format!(
                "syncing - missing {missing_coords} unit(s) and behind by {rounds_behind} rounds"
            ),
        }
    }

    fn format_missing_coords(c: &[(usize, Round)]) -> String {
        c.iter()
            .sorted()
            .group_by(|(creator, _)| *creator)
            .into_iter()
            .map(|(creator, rounds)| {
                // compress consecutive rounds into one interval to shorten logs
                let mut intervals: Vec<(Round, Round)> = Vec::new();
                for (_, round) in rounds {
                    if matches!(intervals.last(), Some(interval) if interval.1 == round-1) {
                        intervals.last_mut().unwrap().1 = *round;
                    } else {
                        intervals.push((*round, *round));
                    }
                }

                let intervals_str = intervals
                    .into_iter()
                    .map(|(begin, end)| {
                        if begin == end {
                            format!("{begin}")
                        } else if begin + 1 == end {
                            format!("{begin}, {end}")
                        } else {
                            format!("[{begin}-{end}]")
                        }
                    })
                    .format(", ");

                format!("{{Creator {creator}: {intervals_str}}}")
            })
            .join(", ")
    }
}

impl<'a, H: Hasher> Display for RunwayStatus<'a, H> {
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        write!(f, "Runway status report: {}", self.short_report())?;
        if !self.missing_coords.is_empty() {
            let v_coords: Vec<(usize, Round)> = self
                .missing_coords
                .iter()
                .map(|uc| (uc.creator().into(), uc.round()))
                .collect();
            write!(
                f,
                "; missing coords - {}",
                Self::format_missing_coords(&v_coords)
            )?;
        }
        if !self.missing_parents.is_empty() {
            write!(f, "; missing parents - {:?}", self.missing_parents)?;
        }
        write!(f, ".")?;
        Ok(())
    }
}

struct RunwayConfig<H: Hasher, D: Data, FH: FinalizationHandler<D>, MK: MultiKeychain> {
    finalization_handler: FH,
    backup_units_for_saver: Sender<DagUnit<H, D, MK>>,
    backup_units_from_saver: Receiver<DagUnit<H, D, MK>>,
    alerts_for_alerter: Sender<Alert<H, D, MK::Signature>>,
    notifications_from_alerter: Receiver<ForkingNotification<H, D, MK::Signature>>,
    unit_messages_from_network: Receiver<RunwayNotificationIn<H, D, MK::Signature>>,
    unit_messages_for_network: Sender<RunwayNotificationOut<H, D, MK::Signature>>,
    responses_for_collection: Sender<CollectionResponse<H, D, MK>>,
    parents_for_creator: Sender<DagUnit<H, D, MK>>,
    resolved_requests: Sender<Request<H>>,
    new_units_from_creation: Receiver<SignedUnit<H, D, MK>>,
}

impl<H, D, FH, MK> Runway<H, D, FH, MK>
where
    H: Hasher,
    D: Data,
    FH: FinalizationHandler<D>,
    MK: MultiKeychain,
{
    fn new(config: RunwayConfig<H, D, FH, MK>, keychain: MK, validator: Validator<MK>) -> Self {
        let n_members = keychain.node_count();
        let RunwayConfig {
            finalization_handler,
            backup_units_for_saver,
            backup_units_from_saver,
            alerts_for_alerter,
            notifications_from_alerter,
            unit_messages_from_network,
            unit_messages_for_network,
            responses_for_collection,
            parents_for_creator,
            resolved_requests,
            new_units_from_creation,
        } = config;
        let store = UnitStore::new(n_members);
        let dag = Dag::new(validator);
        let ordering = Ordering::new(finalization_handler);

        Runway {
            store,
            keychain,
            dag,
            ordering,
            missing_coords: HashSet::new(),
            missing_parents: HashSet::new(),
            resolved_requests,
            alerts_for_alerter,
            notifications_from_alerter,
            unit_messages_from_network,
            unit_messages_for_network,
            parents_for_creator,
            backup_units_for_saver,
            backup_units_from_saver,
            responses_for_collection,
            new_units_from_creation,
            exiting: false,
        }
    }

    fn index(&self) -> NodeIndex {
        self.keychain.index()
    }

    fn handle_dag_result(&mut self, result: DagResult<H, D, MK>) {
        let DagResult {
            units,
            requests,
            alerts,
        } = result;
        for unit in units {
            self.on_unit_reconstructed(unit);
        }
        for request in requests {
            self.on_reconstruction_request(request);
        }
        for alert in alerts {
            if self.alerts_for_alerter.unbounded_send(alert).is_err() {
                warn!(target: "AlephBFT-runway", "{:?} Channel to alerter should be open", self.index());
                self.exiting = true;
            }
        }
    }

    fn on_unit_received(&mut self, unit: UncheckedSignedUnit<H, D, MK::Signature>) {
        let result = self.dag.add_unit(unit, &self.store);
        self.handle_dag_result(result);
    }

    fn on_unit_message(&mut self, message: RunwayNotificationIn<H, D, MK::Signature>) {
        match message {
            RunwayNotificationIn::NewUnit(u) => {
                trace!(target: "AlephBFT-runway", "{:?} New unit received {:?}.", self.index(), &u);
                self.on_unit_received(u)
            }

            RunwayNotificationIn::Request(request, node_id) => match request {
                Request::Coord(coord) => {
                    trace!(target: "AlephBFT-runway", "{:?} Coords request received {:?}.", self.index(), coord);
                    self.on_request_coord(node_id, coord)
                }
                Request::Parents(u_hash) => {
                    trace!(target: "AlephBFT-runway", "{:?} Parents request received {:?}.", self.index(), u_hash);
                    self.on_request_parents(node_id, u_hash)
                }
                Request::NewestUnit(salt) => {
                    trace!(target: "AlephBFT-runway", "{:?} Newest unit request received {:?}.", self.index(), salt);
                    self.on_request_newest(node_id, salt)
                }
            },

            RunwayNotificationIn::Response(res) => match res {
                Response::Coord(u) => {
                    trace!(target: "AlephBFT-runway", "{:?} Fetch response received {:?}.", self.index(), &u);
                    self.on_unit_received(u)
                }
                Response::Parents(u_hash, parents) => {
                    trace!(target: "AlephBFT-runway", "{:?} Response parents received {:?}.", self.index(), u_hash);
                    self.on_parents_response(u_hash, parents)
                }
                Response::NewestUnit(response) => {
                    trace!(target: "AlephBFT-runway", "{:?} Response newest unit received from {:?}.", self.index(), response.index());
                    let res = self.responses_for_collection.unbounded_send(response);
                    if res.is_err() {
                        debug!(target: "AlephBFT-runway", "{:?} Could not send response to collection ({:?}).", self.index(), res)
                    }
                }
            },
        }
    }

    fn resolve_missing_coord(&mut self, coord: &UnitCoord) {
        if self.missing_coords.remove(coord) {
            self.send_resolved_request_notification(Request::Coord(*coord));
        }
    }

    fn on_request_coord(&mut self, node_id: NodeIndex, coord: UnitCoord) {
        debug!(target: "AlephBFT-runway", "{:?} Received fetch request for coord {:?} from {:?}.", self.index(), coord, node_id);
        match self.store.canonical_unit(coord).cloned() {
            Some(su) => {
                trace!(target: "AlephBFT-runway", "{:?} Answering fetch request for coord {:?} from {:?}.", self.index(), coord, node_id);
                self.send_message_for_network(RunwayNotificationOut::Response(
                    Response::Coord(su.unpack().into()),
                    node_id,
                ));
            }
            None => {
                trace!(target: "AlephBFT-runway", "{:?} Not answering fetch request for coord {:?}. Unit not in store.", self.index(), coord);
            }
        }
    }

    fn on_request_parents(&mut self, node_id: NodeIndex, u_hash: H::Hash) {
        debug!(target: "AlephBFT-runway", "{:?} Received parents request for hash {:?} from {:?}.", self.index(), u_hash, node_id);

        match self.store.unit(&u_hash) {
            Some(unit) => {
                trace!(target: "AlephBFT-runway", "{:?} Answering parents request for hash {:?} from {:?}.", self.index(), u_hash, node_id);
                let parents = unit
                    .parents()
                    .values()
                    .map(|parent_hash| {
                        self.store
                            .unit(parent_hash)
                            .expect("We add units to the store in order.")
                            .clone()
                            .unpack()
                            .into_unchecked()
                    })
                    .collect();
                self.send_message_for_network(RunwayNotificationOut::Response(
                    Response::Parents(u_hash, parents),
                    node_id,
                ));
            }
            None => {
                trace!(target: "AlephBFT-runway", "{:?} Not answering parents request for hash {:?}. Unit not in DAG yet.", self.index(), u_hash);
            }
        }
    }

    fn on_request_newest(&mut self, requester: NodeIndex, salt: u64) {
        let unit = self
            .store
            .canonical_units(requester)
            .last()
            .map(|unit| unit.clone().unpack().into_unchecked());
        let response = NewestUnitResponse::new(requester, self.index(), unit, salt);

        let signed_response = Signed::sign(response, &self.keychain).into_unchecked();

        if let Err(e) =
            self.unit_messages_for_network
                .unbounded_send(RunwayNotificationOut::Response(
                    Response::NewestUnit(signed_response),
                    requester,
                ))
        {
            error!(target: "AlephBFT-runway", "Unable to send response to network: {}", e);
        }
    }

    fn on_parents_response(
        &mut self,
        u_hash: H::Hash,
        parents: Vec<UncheckedSignedUnit<H, D, MK::Signature>>,
    ) {
        if self.store.unit(&u_hash).is_some() {
            trace!(target: "AlephBFT-runway", "{:?} We got parents response but already imported the unit.", self.index());
            return;
        }
        let result = self.dag.add_parents(u_hash, parents, &self.store);
        self.handle_dag_result(result);
    }

    fn on_forking_notification(&mut self, notification: ForkingNotification<H, D, MK::Signature>) {
        let result = self
            .dag
            .process_forking_notification(notification, &self.store);
        self.handle_dag_result(result);
    }

    fn resolve_missing_parents(&mut self, u_hash: &H::Hash) {
        if self.missing_parents.remove(u_hash) {
            self.send_resolved_request_notification(Request::Parents(*u_hash));
        }
    }

    fn on_reconstruction_request(&mut self, request: ReconstructionRequest<H>) {
        use ReconstructionRequest::*;
        match request {
            Coord(coord) => {
                self.on_missing_coord(coord);
            }
            ParentsOf(h) => {
                self.on_wrong_control_hash(h);
            }
        }
    }

    fn on_unit_reconstructed(&mut self, unit: DagUnit<H, D, MK>) {
        let unit_hash = unit.hash();
        trace!(target: "AlephBFT-runway", "Unit {:?} {} reconstructed.", unit_hash, unit.coord());
        if self.backup_units_for_saver.unbounded_send(unit).is_err() {
            error!(target: "AlephBFT-runway", "{:?} A unit couldn't be sent to backup: {:?}.", self.index(), unit_hash);
        }
    }

    fn on_unit_backup_saved(&mut self, unit: DagUnit<H, D, MK>) {
        let unit_hash = unit.hash();
        self.store.insert(unit.clone());
        self.dag.finished_processing(&unit_hash);
        self.resolve_missing_parents(&unit_hash);
        self.resolve_missing_coord(&unit.coord());
        if self
            .parents_for_creator
            .unbounded_send(unit.clone())
            .is_err()
        {
            warn!(target: "AlephBFT-runway", "Creator channel should be open.");
            self.exiting = true;
        }
        let unpacked_unit = unit.clone().unpack();
        self.send_message_for_network(RunwayNotificationOut::NewAnyUnit(
            unpacked_unit.clone().into(),
        ));

        if unit.creator() == self.index() {
            trace!(target: "AlephBFT-runway", "{:?} Sending a unit {:?}.", self.index(), unit.hash());
            self.send_message_for_network(RunwayNotificationOut::NewSelfUnit(unpacked_unit.into()));
        }
        self.ordering.add_unit(unit.clone());
    }

    fn on_missing_coord(&mut self, coord: UnitCoord) {
        trace!(target: "AlephBFT-runway", "{:?} Dealing with missing coord notification {:?}.", self.index(), coord);
        if self.store.canonical_unit(coord).is_none() {
            let new_request = self.missing_coords.insert(coord);
            if new_request {
                self.send_message_for_network(RunwayNotificationOut::Request(Request::Coord(
                    coord,
                )));
            }
        }
    }

    fn on_wrong_control_hash(&mut self, u_hash: H::Hash) {
        trace!(target: "AlephBFT-runway", "{:?} Dealing with wrong control hash notification {:?}.", self.index(), u_hash);
        if self.missing_parents.insert(u_hash) {
            self.send_message_for_network(RunwayNotificationOut::Request(Request::Parents(u_hash)));
        }
    }

    fn send_message_for_network(
        &mut self,
        notification: RunwayNotificationOut<H, D, MK::Signature>,
    ) {
        if self
            .unit_messages_for_network
            .unbounded_send(notification)
            .is_err()
        {
            warn!(target: "AlephBFT-runway", "{:?} unit_messages_for_network channel should be open", self.index());
            self.exiting = true;
        }
    }

    fn send_resolved_request_notification(&mut self, notification: Request<H>) {
        if self.resolved_requests.unbounded_send(notification).is_err() {
            warn!(target: "AlephBFT-runway", "{:?} resolved_requests channel should be open", self.index());
            self.exiting = true;
        }
    }

    fn status(&self) -> RunwayStatus<'_, H> {
        RunwayStatus {
            missing_coords: &self.missing_coords,
            missing_parents: &self.missing_parents,
            dag_status: self.dag.status(),
            store_status: self.store.status(),
        }
    }

    fn status_report(&self) {
        info!(target: "AlephBFT-runway", "{}", self.status());
    }

    async fn run(
        mut self,
        data_from_backup: oneshot::Receiver<Vec<UncheckedSignedUnit<H, D, MK::Signature>>>,
        mut terminator: Terminator,
    ) {
        let index = self.index();
        let data_from_backup = data_from_backup.fuse();
        pin_mut!(data_from_backup);

        let status_ticker_delay = Duration::from_secs(10);
        let mut status_ticker = Delay::new(status_ticker_delay).fuse();

        match data_from_backup.await {
            Ok(units) => {
                for unit in units {
                    self.on_unit_received(unit);
                }
            }
            Err(e) => {
                error!(target: "AlephBFT-runway", "{:?} Units message from backup channel closed: {:?}", index, e);
                return;
            }
        }

        debug!(target: "AlephBFT-runway", "{:?} Runway started.", index);
        loop {
            futures::select! {
                signed_unit = self.new_units_from_creation.next() => match signed_unit {
                    Some(signed_unit) => self.on_unit_received(signed_unit.into()),
                    None => {
                        error!(target: "AlephBFT-runway", "{:?} Creation stream closed.", index);
                        break;
                    }
                },

                notification = self.notifications_from_alerter.next() => match notification {
                    Some(notification) => {
                        trace!(target: "AlephBFT-runway", "Received alerter notification: {:?}.", notification);
                        self.on_forking_notification(notification);
                    },
                    None => {
                        error!(target: "AlephBFT-runway", "{:?} Alert notification stream closed.", index);
                        break;
                    }
                },

                event = self.unit_messages_from_network.next() => match event {
                    Some(event) => self.on_unit_message(event),
                    None => {
                        error!(target: "AlephBFT-runway", "{:?} Unit message stream closed.", index);
                        break;
                    }
                },

                message = self.backup_units_from_saver.next() => match message {
                    Some(unit) => self.on_unit_backup_saved(unit),
                    None => {
                        error!(target: "AlephBFT-runway", "{:?} Saved units receiver closed.", index);
                    }
                },

                _ = &mut status_ticker => {
                    self.status_report();
                    status_ticker = Delay::new(status_ticker_delay).fuse();
                },

                _ = terminator.get_exit().fuse() => {
                    debug!(target: "AlephBFT-runway", "{:?} received exit signal", index);
                    self.exiting = true;
                }
            }

            if self.exiting {
                debug!(target: "AlephBFT-runway", "{:?} Runway decided to exit.", index);
                terminator.terminate_sync().await;
                break;
            }
        }

        debug!(target: "AlephBFT-runway", "{:?} Run ended.", index);
    }
}

pub(crate) struct NetworkIO<H: Hasher, D: Data, MK: MultiKeychain> {
    pub(crate) alert_messages_for_network: Sender<(NetworkMessage<H, D, MK>, Recipient)>,
    pub(crate) alert_messages_from_network: Receiver<NetworkMessage<H, D, MK>>,
    pub(crate) unit_messages_for_network: Sender<RunwayNotificationOut<H, D, MK::Signature>>,
    pub(crate) unit_messages_from_network: Receiver<RunwayNotificationIn<H, D, MK::Signature>>,
    pub(crate) resolved_requests: Sender<Request<H>>,
}

#[cfg(feature = "initial_unit_collection")]
fn initial_unit_collection<'a, H: Hasher, D: Data, MK: MultiKeychain>(
    keychain: &'a MK,
    validator: &'a Validator<MK>,
    unit_messages_for_network: &Sender<RunwayNotificationOut<H, D, MK::Signature>>,
    unit_collection_sender: oneshot::Sender<Round>,
    responses_from_runway: Receiver<CollectionResponse<H, D, MK>>,
    resolved_requests: Sender<Request<H>>,
) -> Result<impl Future<Output = ()> + 'a, ()> {
    let (collection, salt) = Collection::new(keychain, validator);
    let notification = RunwayNotificationOut::Request(Request::NewestUnit(salt));

    if let Err(e) = unit_messages_for_network.unbounded_send(notification) {
        error!(target: "AlephBFT-runway", "Unable to send the newest unit request: {}", e);
        return Err(());
    };

    let collection = CollectionIO::new(
        unit_collection_sender,
        responses_from_runway,
        resolved_requests,
        collection,
    );
    Ok(collection.run())
}

#[cfg(not(feature = "initial_unit_collection"))]
fn trivial_start(
    starting_round_sender: oneshot::Sender<Round>,
) -> Result<impl Future<Output = ()>, ()> {
    if let Err(e) = starting_round_sender.send(0) {
        error!(target: "AlephBFT-runway", "Unable to send the starting round: {}", e);
        return Err(());
    }
    Ok(async {})
}

pub struct RunwayIO<
    H: Hasher,
    D: Data,
    MK: MultiKeychain,
    W: AsyncWrite + Send + Sync + 'static,
    R: AsyncRead + Send + Sync + 'static,
    DP: DataProvider<D>,
    FH: FinalizationHandler<D>,
> {
    pub data_provider: DP,
    pub finalization_handler: FH,
    pub backup_write: W,
    pub backup_read: R,
    _phantom: PhantomData<(H, D, MK::Signature)>,
}

impl<
        H: Hasher,
        D: Data,
        MK: MultiKeychain,
        W: AsyncWrite + Send + Sync + 'static,
        R: AsyncRead + Send + Sync + 'static,
        DP: DataProvider<D>,
        FH: FinalizationHandler<D>,
    > RunwayIO<H, D, MK, W, R, DP, FH>
{
    pub fn new(
        data_provider: DP,
        finalization_handler: FH,
        backup_write: W,
        backup_read: R,
    ) -> Self {
        RunwayIO {
            data_provider,
            finalization_handler,
            backup_write,
            backup_read,
            _phantom: PhantomData,
        }
    }
}

pub(crate) async fn run<H, D, US, UL, MK, DP, FH, SH>(
    config: Config,
    runway_io: RunwayIO<H, D, MK, US, UL, DP, FH>,
    keychain: MK,
    spawn_handle: SH,
    network_io: NetworkIO<H, D, MK>,
    mut terminator: Terminator,
) where
    H: Hasher,
    D: Data,
    US: AsyncWrite + Send + Sync + 'static,
    UL: AsyncRead + Send + Sync + 'static,
    DP: DataProvider<D>,
    FH: FinalizationHandler<D>,
    MK: MultiKeychain,
    SH: SpawnHandle,
{
    let RunwayIO {
        data_provider,
        finalization_handler,
        backup_write,
        backup_read,
        _phantom: _,
    } = runway_io;

    let (new_units_for_runway, new_units_from_creation) = mpsc::unbounded();

    let (parents_for_creator, parents_from_runway) = mpsc::unbounded();
    let creation_terminator = terminator.add_offspring_connection("creator");
    let creation_config = config.clone();
    let (starting_round_sender, starting_round) = oneshot::channel();

    let creation_keychain = keychain.clone();
    let creation_handle = spawn_handle
        .spawn_essential("runway/creation", async move {
            creation::run(
                creation_config,
                creation::IO {
                    outgoing_units: new_units_for_runway,
                    incoming_parents: parents_from_runway,
                    data_provider,
                },
                creation_keychain,
                starting_round,
                creation_terminator,
            )
            .await
        })
        .shared();
    let creator_handle_for_panic = creation_handle.clone();
    let creator_panic_handle = async move {
        if creator_handle_for_panic.await.is_err() {
            return;
        }
        pending().await
    }
    .fuse();
    pin_mut!(creator_panic_handle);
    let creation_handle = creation_handle.fuse();

    let (backup_units_for_saver, backup_units_from_runway) = mpsc::unbounded();
    let (backup_units_for_runway, backup_units_from_saver) = mpsc::unbounded();

    let backup_saver_terminator = terminator.add_offspring_connection("AlephBFT-backup-saver");
    let backup_saver_handle = spawn_handle.spawn_essential("runway/backup_saver", {
        let mut backup_saver = BackupSaver::new(
            backup_units_from_runway,
            backup_units_for_runway,
            backup_write,
        );
        async move {
            backup_saver.run(backup_saver_terminator).await;
        }
    });
    let mut backup_saver_handle = backup_saver_handle.fuse();

    let (alert_notifications_for_units, notifications_from_alerter) = mpsc::unbounded();
    let (alerts_for_alerter, alerts_from_units) = mpsc::unbounded();

    let alerter_terminator = terminator.add_offspring_connection("AlephBFT-alerter");
    let alerter_keychain = keychain.clone();
    let alert_messages_for_network = network_io.alert_messages_for_network;
    let alert_messages_from_network = network_io.alert_messages_from_network;
    let alerter_handler =
        crate::alerts::Handler::new(alerter_keychain.clone(), config.session_id());

    let mut alerter_service = crate::alerts::Service::new(
        alerter_keychain,
        crate::alerts::IO {
            messages_for_network: alert_messages_for_network,
            messages_from_network: alert_messages_from_network,
            notifications_for_units: alert_notifications_for_units,
            alerts_from_units,
        },
        alerter_handler,
    );

    let mut alerter_handle = spawn_handle
        .spawn_essential("runway/alerter", async move {
            alerter_service.run(alerter_terminator).await;
        })
        .fuse();

    let index = keychain.index();
    let validator = Validator::new(config.session_id(), keychain.clone(), config.max_round());
    let (responses_for_collection, responses_from_runway) = mpsc::unbounded();
    let (unit_collections_sender, unit_collection_result) = oneshot::channel();
    let (loaded_data_tx, loaded_data_rx) = oneshot::channel();
    let session_id = config.session_id();

    let backup_loading_handle = spawn_handle
        .spawn_essential("runway/loading", {
            let mut backup_loader = BackupLoader::new(backup_read, index, session_id);
            async move {
                backup_loader
                    .run(
                        loaded_data_tx,
                        starting_round_sender,
                        unit_collection_result,
                    )
                    .await
            }
        })
        .fuse();
    pin_mut!(backup_loading_handle);

    #[cfg(feature = "initial_unit_collection")]
    let starting_round_handle = match initial_unit_collection(
        &keychain,
        &validator,
        &network_io.unit_messages_for_network,
        unit_collections_sender,
        responses_from_runway,
        network_io.resolved_requests.clone(),
    ) {
        Ok(handle) => handle.fuse(),
        Err(_) => return,
    };
    #[cfg(not(feature = "initial_unit_collection"))]
    let starting_round_handle = match trivial_start(unit_collections_sender) {
        Ok(handle) => handle.fuse(),
        Err(_) => return,
    };
    pin_mut!(starting_round_handle);

    let runway_handle = spawn_handle
        .spawn_essential("runway", {
            let runway_config = RunwayConfig {
                finalization_handler,
                backup_units_for_saver,
                backup_units_from_saver,
                alerts_for_alerter,
                notifications_from_alerter,
                unit_messages_from_network: network_io.unit_messages_from_network,
                unit_messages_for_network: network_io.unit_messages_for_network,
                parents_for_creator,
                responses_for_collection,
                resolved_requests: network_io.resolved_requests,
                new_units_from_creation,
            };
            let runway_terminator = terminator.add_offspring_connection("AlephBFT-runway");
            let validator = validator.clone();
            let keychain = keychain.clone();
            let runway = Runway::new(runway_config, keychain, validator);

            async move { runway.run(loaded_data_rx, runway_terminator).await }
        })
        .fuse();
    pin_mut!(runway_handle);

    loop {
        futures::select! {
            _ = runway_handle => {
                debug!(target: "AlephBFT-runway", "{:?} Runway task terminated early.", index);
                break;
            },
            _ = alerter_handle => {
                debug!(target: "AlephBFT-runway", "{:?} Alerter task terminated early.", index);
                break;
            },
            _ = creator_panic_handle => {
                debug!(target: "AlephBFT-runway", "{:?} creator task terminated early with its task being dropped.", index);
                break;
            },
            _ = backup_saver_handle => {
                debug!(target: "AlephBFT-runway", "{:?} Backup saving task terminated early.", index);
                break;
            },
            _ = starting_round_handle => {
                debug!(target: "AlephBFT-runway", "{:?} Starting round task terminated.", index);
            },
            _ = backup_loading_handle => {
                debug!(target: "AlephBFT-runway", "{:?} Backup loading task terminated.", index);
            },
            _ = terminator.get_exit().fuse() => {
                break;
            }
        }
    }

    debug!(target: "AlephBFT-runway", "{:?} Ending run.", index);
    terminator.terminate_sync().await;

    handle_task_termination(creation_handle, "AlephBFT-runway", "Creator", index).await;
    handle_task_termination(alerter_handle, "AlephBFT-runway", "Alerter", index).await;
    handle_task_termination(runway_handle, "AlephBFT-runway", "Runway", index).await;
    handle_task_termination(backup_saver_handle, "AlephBFT-runway", "BackupSaver", index).await;

    debug!(target: "AlephBFT-runway", "{:?} Runway ended.", index);
}

#[cfg(test)]
mod tests {
    use crate::runway::RunwayStatus;
    use aleph_bft_mock::Hasher64;

    #[test]
    pub fn formats_missing_coords() {
        let format_missing_coords = RunwayStatus::<Hasher64>::format_missing_coords;
        assert_eq!(format_missing_coords(&[]), "");
        assert_eq!(format_missing_coords(&[(0, 13)]), "{Creator 0: 13}");
        assert_eq!(
            format_missing_coords(&[(0, 1), (0, 2)]),
            "{Creator 0: 1, 2}"
        );
        assert_eq!(
            format_missing_coords(&[(0, 1), (0, 2), (0, 3)]),
            "{Creator 0: [1-3]}"
        );
        assert_eq!(
            format_missing_coords(&[
                (0, 1),
                (0, 3),
                (0, 4),
                (0, 5),
                (0, 6),
                (0, 9),
                (0, 10),
                (0, 12)
            ]),
            "{Creator 0: 1, [3-6], 9, 10, 12}"
        );
        assert_eq!(
            format_missing_coords(&[(1, 3), (0, 1), (1, 1), (3, 0)]),
            "{Creator 0: 1}, {Creator 1: 1, 3}, {Creator 3: 0}"
        );
    }
}
