name: Version bump check for code changes in the aleph-bft-rmc package

on:
  pull_request:
    branches:
      - main
    paths:
      - 'rmc/src/**'

jobs:
  check-version-bumped-rmc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check-cargo-toml-version-bumped
        run: |
          if ! git diff HEAD origin/main -- rmc/Cargo.toml | grep -q '^+version ='; then
            echo "None of commits in this PR has changed version in rmc/Cargo.toml!"
            exit 1
          fi
        shell: bash
